name: Docker builds

on:
  push:
    branches:
      - 'ghost'
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
  pull_request:

jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          submodules: true
          
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=date::$(date +%Y-%m-%dT%H-%M-%S)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up Docker Buildx
        uses: docker/Setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ github.ref == 'refs/heads/ghost' }}
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          # Only push when on ghost
          push: ${{ github.ref == 'refs/heads/ghost' && github.event_name == 'push' }}
          tags: |
            ghcr.io/marigold-dev/winefactory:latest
            ghcr.io/marigold-dev/winefactory:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

